name: shadertoy_moor
version: 1.0.1
description: >-
  A implementation of the shadertoy storage API using
  Moor as the storage backend
homepage: https://github.com/ivoleitao/shadertoy_moor

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  enum_to_string: ^1.0.14
  moor: ^3.4.0
  shadertoy_api: ^1.0.18
  # shadertoy_api:
  #  path: ../shadertoy_api

dev_dependencies:
  pedantic: ^1.9.2
  build_runner: ^1.10.12
  test: ^1.15.7
  moor_generator: ^3.4.0

scripts: derry.yaml
