name: shadertoy_moor
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/ivoleitao/shadertoy_moor

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  enum_to_string: ^1.0.9
  moor: ^3.3.0
  #shadertoy_api: ^1.0.4
  shadertoy_api:
    path: ../shadertoy_api

dev_dependencies:
  pedantic: ^1.9.2
  build_runner: ^1.10.0
  build_verify: ^1.1.1
  test: ^1.15.3
  moor_generator: ^3.3.0
