name: shadertoy_moor
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
# author: Ivo Leitão <ivo.leitao@sky.uk>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  enum_to_string: ^1.0.8
  moor: ^2.1.1
  shadertoy_api: ^1.0.0-dev.6
  #shadertoy_api:
  #  path: ../shadertoy_api

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.7.2
  build_verify: ^1.1.1
  test: ^1.9.4
  moor_generator: ^2.1.1
