name: shadertoy_moor
version: 1.0.0-dev.2
description: >-
  A implementation of the shadertoy storage API using
  Moor as the storage backend
homepage: https://github.com/ivoleitao/shadertoy_moor

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  enum_to_string: ^1.0.14
  moor: ^3.4.0
  shadertoy_api: ^1.0.9
  #shadertoy_api:
  #  path: ../shadertoy_api

dev_dependencies:
  pedantic: ^1.9.2
  build_runner: ^1.10.12
  build_verify: ^1.1.1
  test: ^1.15.7
  test_coverage: ^0.5.0
  moor_generator: ^3.4.0

scripts: derry.yaml
